### ISSUE TITLE
`Ripgrep-all` runs very slowly for the first time after the computer starts.

### ISSUE THREAD

**Issue by hongyi-zhao** [phiresky/ripgrep-all#131]
On Ubuntu 20.04.3 LTS, I'm using the self-compiled git master version of `ripgrep-all`. I noticed that it runs very slowly for the first time after the computer starts. Therefore, I think it must work based on caching mechanism. The problem is how to maintain the cache after the computer is restarted to maximize the operation efficiency.

Any hints for this problem will be highly appreciated.

Regards,
HZ

**Comment by phiresky** [comment]
This is not really fixable without scanning both the whole file system and loading the cache file into RAM cache.

The easiest way to "fix" this would be to add a `rga` command that is similar to what you want to run to your autostart so it forces the OS to cache the relevant filesystem data. Or even something like like `cat ~/.cache/ripgrep-all/data.mdb >/dev/null`.

**Comment by hongyi-zhao** [comment]
> The easiest way to "fix" this would be to add a `rga` command that is similar to what you want to run to your autostart so it forces the OS to cache the relevant filesystem data. 

Do you mean run something like the following automatically in a script file invoked by an autostart desktop entry?

```shell
$ rga 'blabla'
```
> Or even something like `cat ~/.cache/ripgrep-all/data.mdb >/dev/null`.

What does this mean? How can I use this technique to quickly reuse the cache after restarting the computer?

**Comment by phiresky** [comment]
Yes exactly. 

rg and rga are fast because operating systems automatically cache filesystem metadata (directory structures, filenames etc) as well as filesystem data (file contents) if your RAM is big enough, and if you run multiple queries you usually have heavily overlapping data.

So you can just run whatever command you want that makes the OS put the stuff you need later into cache. the `cat` command I sent would make the OS cache the ripgrep-all cache file. running `rga 'blabla'` would make it cache all the directory structures of the location it's run in.

**Comment by hongyi-zhao** [comment]
Some other questions: 

1. Suppose I have exactly the same pdf file stored in different locations, in this case, does ripgrep-all cache all these files or only one of them?
2. If I have two basically identical pdf files, for example, one has some manually added comments and the other is the original version, in this case, what is the caching algorithm used by ripgrep-all for these two files?

**Comment by phiresky** [comment]
1. The key into the cache (currently) is `(fname, mtime)` so if you have multiple copies of the same file it will store them in cache multiple times. This could be changed to be a file hash but that has the disadvantage that it would have to read the whole file first  (to figure out the file identity) before it can begin to return results
2. They are treated as completely separate files. Detecting this would be pretty hard and require file-type specific logic.

The content of the cache is simply a compressed plain-text version of the documents, there's nothing really smart going on there, but for e.g. PDFs almost all of the search time is taken up by reading the PDF (including images etc) and extracting the text from the PDF, that's why rga is fast for those.

**Comment by hongyi-zhao** [comment]
Some of my ideas:

All text-based searches must first extract the original content, such as PDF, and then convert it to text. So, what about the following logic for this type of search?

1. Extract the text content from these files to construct the cache for each original file.
2. For different files that share so much similar content, only store a main file of them, and the diff's for others.

**Comment by phiresky** [comment]
That might make sense, but I doubt it would really improve storage much and in turn would add a lot of complexity. At that point it probably makes more sense to use / create a "real" full text search tool that doesn't just store a dump of the text content but stores a real inverted index.

Like based on lucene, sqlite FTS, etc. I know some such tools exist for searching in personal file but I'm not really a user of them so I can't really name them.

**Comment by hongyi-zhao** [comment]
Can the full text search tools like lucene, sqlite FTS, etc. also support a variety of different types of files?
