### ISSUE TITLE
Option to suppress

### ISSUE THREAD

**Issue by rsuhada** [phiresky/ripgrep-all#21]
Would it be possible to add a flag to automatically skip files where adapter fails?
My searches are sometime polluted by quite verbose errors, e.g.:

    notebook/symetrical_components.ipynb: preprocessor command failed: '"rga-preproc" "notebook/symetrical_components.ipynb"': 
    -------------------------------------------------------------------------------
    adapter: pandoc
    Unknown reader: ipynb
    Error: Broken pipe (os error 32)
    -------------------------------------------------------------------------------

(I'm not sure why it attempts to use pandoc on jupyter notebooks, but that's a separate issue :))

**Comment by phiresky** [comment]
because jupyter notebooks (json) are pretty unreadable and pandoc can convert them to plain text or markdown :) Your pandoc version is probably too old for that. But I've also had problems because it fails even on pretty irrelevant errors in those notebooks.

You can actually suppress errors using `--no-messages` (#7), though that also supresses e.g. I/O errors.

**Comment by rsuhada** [comment]
Thanks!  `--no-message` works great for me (it's not yet in help yet, that's why I missed it).

**Comment by phiresky** [comment]
Yeah, that's because it's from `rg`s args. You can see it in `rga --rg-help`. I don't want to copy all of that to normal `--help` because it would be very long.. Maybe I should mention flags that are especially useful for `rga` somewhere..
