### ISSUE TITLE
Poppler pdftotext problem

### ISSUE THREAD

**Issue by bruno299792** [phiresky/ripgrep-all#243]
Hi,

need your help

i know rga use poppler's pdftotext to read pdf, but the whole poppler is too large, and rga only use small part of it
is there any possible to install pdftotext only, or can I use xpdfreader's pdftotext binary instead?

**Comment by lafrenierejm** [comment]
> is there any possible to install pdftotext only

I haven't personally verified this, but since `pdftotext` has [its own entry](https://gitlab.freedesktop.org/poppler/poppler/-/blob/master/utils/CMakeLists.txt#L135-142) in poppler's CMake file I suspect you _could_ build and use just that one utility.

That said, `poppler` and `poppler-utils` are often available as two separate packages with `pdftotext` included in the latter. If that is the case for your OS, you should be able to get away with only installing the `-utils` package and _not_ the full `poppler` package.

> can I use xpdfreader's pdftotext binary instead?

You should be able to as long as the CLI of xpdfreader's `pdftotext` binary is compatible with the one offered by poppler. ripgrep-all just looks for the [first entry in your `PATH` named "poppler"](https://github.com/phiresky/ripgrep-all/blob/6b79490d23473d76425f3a1a44e3554144ba7996/src/adapters/custom.rs#L128); if xpdfreader's `pdftotext` is found before poppler's (or if you don't have the binary from poppler on your PATH at all) then `rga` will use it.

**Comment by phiresky** [comment]
the xpdfreader binary is not compatible, it does not support stdin input. 

you can use whatever means you want to get the pdftotext binary, but by default it's dynamically linked to `libpoppler.so` on my system. I'm sure it's possible to compile it statically if you want, but it's probably not going to save much size.

Closing as off topic, this question isn't really related to rga
