### ISSUE TITLE
Enable searching of local RPMs

### ISSUE THREAD

**Issue by svenstaro** [phiresky/ripgrep-all#28]
I sometimes have to locate files in a big pool of local RPMs. It would be really neat if this tool supported searching through that.

**Comment by phiresky** [comment]
Good idea. Researching a bit, looks like there's three steps to achieve this:

1. Get the actual data from the rpm, which is a cpio archive. [rpm2cpio](https://git.archlinux.org/svntogit/packages.git/tree/trunk/rpm2cpio?h=packages/rpmextract) is a 30 line shell script (could be bundled) or maybe https://crates.io/crates/rpm-rs which is a rust library that would also allow getting the package metadata which would be useful.
2. Decompress the cpio. Apparently it can use pretty much any compression, with the most common being gz, xz and zstd. This should be handled by just passing it to the existing decompress adapter with mime type detection
3. Extract the cpio and recursively handle all contained files. There's the [cpio-rs](https://docs.rs/cpio/0.2.0/cpio/) library which looks like it should work (it provides an iterator of `Read`s  for the contained files), assuming rpm always uses the SVR4 cpio format.

lesspipe [does it similarily](https://github.com/wofr06/lesspipe/blob/b2c2bc3de0fb93a61e292e3d8e1606382d7684dd/lesspipe.sh.in#L567-L571), though testing it it seems to be broken for me.

Since I don't have a personal need for rpm archives in particular (Arch uses simple tar.* archives for packages) I'm probably not going to spend time implementing this soon, unless I get bored. Of course I'd be happy to merge a PR though!

**Comment by MusiKid** [comment]
I could try to make it with only Rust.

**Comment by svenstaro** [comment]
@MusiKid did you ever get anywhere with your approach?

**Comment by phiresky** [comment]
Starting with 1.0.0, it's possible to add custom adapters [via the config file](https://github.com/phiresky/ripgrep-all/wiki). If someone has a good suggestion for a file type please post it in [show-your-adapter](https://github.com/phiresky/ripgrep-all/discussions/categories/show-your-adapter)
