### ISSUE TITLE
WSL warning for other users

### ISSUE THREAD

**Issue by mleo2003** [phiresky/ripgrep-all#30]
I wanted to use this tool on Windows WSL (with the Ubuntu there), and wanted to give others who also wanted to try this a note on this. The caching library that ripgrep-all uses doesn't work on WSL (which is WSL's fault from what I read online), so if you use it in the default configs, you'll get a ton of warnings. Just disabling the use of the cache makes the warnings go away.

There really isn't a fix on the horizon, but I do know that WSL2 is designed differently, and in the future using that should let everything broken like this "just work".

**Comment by phiresky** [comment]
Thanks for the note! I'm not sure how useful rga is on WSL since it needs to work with the host filesystem anyways which from my understanding of WSL doesn't work well in any case? 

I could add a warning to the readme for other WSL users but I guess if it'll be fixed with WSL2 that's not necessary. What do you think?

Note that disabling the cache significantly reduces the usefulness (at least for my use cases) since some extractors are pretty slow so you don't want to run them repeatedly.

One solution would be to replace the caching system with sqlite which I've already thought about (slightly slower but much better compatibility and familiarity).

**Comment by mleo2003** [comment]
WSL does work with the host filesystem as far as preprocess and scanning/searching goes. It was only erroring while trying to store the preprocess results in the cache.

I figured this ticket/issue could serve as enough warning for anyone attempting to use it (though I didn't know who all would).

I used rga on a directory full of epubs and pdfs, and it didn't seem too slow to me, but I'd love any speed improvements possible. Sqlite would be interesting, if for no other reason than to turn the index into a sort of "personal search engine" for more general queries as well later.

**Comment by phiresky** [comment]
Should be fixed with WSL2

**Comment by nzbart** [comment]
Unfortunately, while it sounds from the name that WSL2 is a new, improved, version of WSL and therefore everyone will upgrade, it's actually quite a different product. I'd imagine most devs will use various combinations of WSL and WSL2 since neither product does everything they need.

The warning may still be useful.
