### ISSUE TITLE
error running pdf search on windows 10 - 64bit

### ISSUE THREAD

**Issue by neelabalan** [phiresky/ripgrep-all#32]
I tried running the pdf search with the adapter "poppler" on both version 0.9.2 and 0.9.3 and I get the following error message. What am I missing here?

```
Reference.pdf: preprocessor command failed: '"rga-preproc" "Reference.pdf"':
-------------------------------------------------------------------------------
adapter: poppler
pdftotext version 4.00
Copyright 1996-2017 Glyph & Cog, LLC
Usage: pdftotext [options] <PDF-file> [<text-file>]
  -f <int>             : first page to convert
  -l <int>             : last page to convert
  -layout              : maintain original physical layout
  -simple              : simple one-column page layout
  -table               : similar to -layout, but optimized for tables
  -lineprinter         : use strict fixed-pitch/height layout
  -raw                 : keep strings in content stream order
  -fixed <number>      : assume fixed-pitch (or tabular) text
  -linespacing <number>: fixed line spacing for LinePrinter mode
  -clip                : separate clipped text
  -nodiag              : discard diagonal text
  -enc <string>        : output text encoding name
  -eol <string>        : output end-of-line convention (unix, dos, or mac)
  -nopgbrk             : don't insert page breaks between pages
  -bom                 : insert a Unicode BOM at the start of the text file
  -opw <string>        : owner password (for encrypted files)
  -upw <string>        : user password (for encrypted files)
  -q                   : don't print any messages or errors
  -cfg <string>        : configuration file to use in place of .xpdfrc
  -v                   : print copyright and version info
  -h                   : print usage information
  -help                : print usage information
  --help               : print usage information
  -?                   : print usage information
Error: The pipe has been ended. (os error 109)
```

**Comment by phiresky** [comment]
Hey

it looks like you are using pdftotext from https://www.xpdfreader.com/index.html

You need to use a version maintained by poppler, since that adds support for reading pdfs from memory (stdin) instead of from the file system, which we need since some files are streamed from archives etc.

It should print something like this without arguments:

```
pdftotext version 0.80.0
Copyright 2005-2019 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
```


Sadly it's somewhat hard to find binaries of poppler for windows, but there's a working one included with the binary windows releases here: https://github.com/phiresky/ripgrep-all/releases

**Comment by neelabalan** [comment]
I used the one provided with the windows release. I didn't install anything other than this.

**Comment by phiresky** [comment]
The version shipped with the windows release of rga is definitely a poppler version (0.68.0). I'm guessing you have a different pdftotext installed globally (in $PATH) from some other program (try just calling `pdftotext` from your shell).

If so, the problem would be the precedence within $PATH. The `lib/` directory gets added to $PATH here:

https://github.com/phiresky/ripgrep-all/blob/52690418ccc1e1b742e9637d947c6e6dbcac31b6/src/bin/rga.rs#L120-L124

And I guess I intentionally gave system version of tools priority since I'm appending to $PATH, not prepending. I'm not sure exactly why, but it can probably be changed without problems. Though maybe I should change that logic anyways since at least on Linux it could be considered a security issue.

**Comment by phiresky** [comment]
In your case / until this is fixed, the workaround would be to simply remove your globally installed pdftotext (you probably don't need it) or replace it with the version shipped with rga.

**Comment by neelabalan** [comment]
mingw64/bin was in the $path. I removed it and it worked. Thank you very much.

**Comment by GlassGruber** [comment]
Hey there are you sure the `pdftotext` binary file is included in latest release? I've encountered the same problem but can't find another `pdftotext` file to add to path. 
Thank you!

**Comment by phiresky** [comment]
They are not included anymore, because that was a huge hack since there aren't even any official poppler binaries for windows. It is expected that for Windows you install rga via chocolatey (which should ship the dependencies) or scoop (needs `poppler` additional I think)

**Comment by GlassGruber** [comment]
Make sense, thank you!
