### ISSUE TITLE
preprocessor command failed: '"rga-preproc" "/Users/user/Desktop/test/test.pdf.zip"

### ISSUE THREAD

**Issue by Gahamelas** [phiresky/ripgrep-all#50]
I am getting this error while executing:

` rga "hello"  ~/Desktop/test/ `

where I have a zip file.
I don't understand from the documentation whether ZIP files need an extra argument or not.
Thanks in advance.

**Comment by phiresky** [comment]
You need to give the full details the program outputs, otherwise I can't help you. Or even better attach a sample file.

**Comment by Gahamelas** [comment]
Apologies.  Here is the problema regarding finding a string in a ZIP file.

```
/~Desktop/test/test.pdf.zip: preprocessor command failed: '"rga-preproc" "~/Desktop/test/test.pdf.zip"': 
-------------------------------------------------------------------------------
adapter: zip
Error: Unsupported Zip archive: The file length is not available in the local header

```-------------------------------------------------------------------------------

**Comment by phiresky** [comment]
Ah. Looks like you hit https://github.com/mvdnes/zip-rs/issues/108. We read zip files in streaming mode (so we don't need unbounded memory), and apparently zip-rs can't handle a specific kind of zip files in this mode.

This could be fixed by reading zip files differently (without streaming) as long as they are read from the file system (not from within another archive), but that would mean more effort and inconsistencies. 

I think this is a wontfix since I myself have not encountered any of these files - at least unless more people complain.

**Comment by Gahamelas** [comment]
Thanks, understood. When you say "For these kinds of archives, only normal reading mode (with seeking) is supported", what does it mean in terms of how shall I do the search? Thanks (I have a folder full of ZIP files).

**Comment by cpick** [comment]
> I think this is a wontfix since I myself have not encountered any of these files - at least unless more people complain.

Completely understandable (and I've seen the research that's already been put into the [underlying issue](https://github.com/zip-rs/zip/issues/108)).  I just wanted to leave a note that I've encountered this error and that I can provide a number of example files for testing if that's helpful.

**Comment by IvanVas** [comment]
I get the same errors.

```
<filename> preprocessor command failed: '"/usr/local/bin/rga-preproc" <filename> 
-------------------------------------------------------------------------------
adapter: zip
Error: Unsupported Zip archive: The file length is not available in the local header
```
