### ISSUE TITLE
request for jar file adapter

### ISSUE THREAD

**Issue by alfonz19** [phiresky/ripgrep-all#61]
it can help further spread your good work (since author or ripgrep decided not to support archives at all) and jar file is just zip file. All is needed to cover this is to register new suffix.

**Comment by phiresky** [comment]
You should be able to work around by using `--rga-accurate` for now which detects file type by content instead of name. But testing a few example files of both apks and jars, it seems like many of them don't work because of mvdnes/zip-rs#108 (see #50), so I'm not sure if it's worth changing unless that can be fixed.

**Comment by alfonz19** [comment]
seems to be working, thanks!
