### ISSUE TITLE
Minimize (and provide option to restore) content adapter errors

### ISSUE THREAD

**Issue by mmastrac** [phiresky/ripgrep-all#7]
I'm searching a local tree with lots of "crap" files where some are invalid, some are misnamed, others are mis-predicted mime types. It would be great to minimize the overall error logging impact of these files to a single line (maybe two at most) to avoid losing my search results in the noise.

**Comment by phiresky** [comment]
Actually aggregating errors is fairly complicated, since then I would need to add inter-process communication. But I can definitely add a `--rga-ignore-errors` option that completely silences them and also reduce the length of errors in general since most of that information isn't useful. I'll look into it later today.

**Comment by phiresky** [comment]
I've reduced the default output when a file preprocessing errors to two lines. In addition, you can pass `--no-messages` to suppress all file-read error messages. Let me know if you think it's not enough.
