### ISSUE TITLE
Sophos AV detects Troj/ZipB-A in https://github.com/phiresky/ripgrep-all/blob/master/exampledir/droste.zip

### ISSUE THREAD

**Issue by diegov** [phiresky/ripgrep-all#73]
See https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/Troj~ZipB-A.aspx

I understand the file was added for a zipbomb testcase, which makes sense, unfortunately sophos caregorises the content under "Viruses and Spyware" which forced me to remove the repo from my company workstation. 

Feel free to close this since I don't think there's a real threat in that zipfile, but I thought I'd leave the issue here for future reference in case other people with Sophos run into the same issue.

Thanks

**Comment by Kristinita** [comment]
### 1. VirusTotal

+ [**VirusTotal check**](https://www.virustotal.com/gui/file/983613c84c7b8a1189fe8984d2764fba1b54c205907b9789778db18a2222803c/detection):

![VirusTotal](https://i.imgur.com/W5xnqAE.png)

8 engines detected this file.

### 2. Suggestion

What if we make the recursion in the `droste.zip` file smaller, so that anti-virus engines do not react to this file?

Thanks.

**Comment by phiresky** [comment]
I still think it's a fun example and useful to test the archive recursion limit in rga. It's not going to blow up your computer.
